<<<<<<< HEAD
compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules
=======
compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules
>>>>>>> 531fee6 (folders added)
